openapi: 3.1.1
info:
  title: Api rest with JPA demo
  description: AA CRUD API rest with Jpa/hibernate (h2) demo project.
  version: 1.0.0-SNAPSHOT
  contact:
    name: Contact the developer
    url: 'https://github.com/ilizin'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'http://swagger.io/terms/'

externalDocs:
  description: Find out more about Swagger
  url: 'https://swagger.io/'

paths:
  /v1/cars:
    get:
      summary: Get all the cars
      tags:
        - Car controller
      parameters:
        - in: query
          name: carInDto
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            $ref: "#/components/schemas/CarInDto"
      responses:
        "200": # status code
          description: Successfully retrieved some data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OkResponseDTO" # Reference to an object
              example:
                value: 2
                responseTime: 10
        "400": # status code
          description: Car not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDTO" # Reference to an object
              example:
                status: 400
                message: The value must be positive
  /v1/car/{carId}:
    get:
      summary: Find a car by id
      tags:
        - Car controller
      parameters:
        - in: path
          name: carId
          required: true
          schema:
            $ref: "#/components/schemas/PrimeInDTO" # Reference to an object
      responses:
        "200": # status code
          description: Successfully retrieved some data
          content:
            application/json:
              schema:
                type: integer
              example:
                value: true
                responseTime: 10
        "400": # status code
          description: Car not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDTO" # Reference to an object
              example:
                status: 400
                message: The value must be positive
    put:
      summary: Update an existing car
      tags:
        - Car controller
      parameters:
        - in: query
          name: carInDto
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            $ref: "#/components/schemas/CarInDto"
      responses:
        "200": # status code
          description: Successfully updated an existing car
          content:
            application/json:
              schema:
                type: integer
              example:
                value: true
                responseTime: 10
        "400": # status code
          description: Car not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDTO" # Reference to an object
              example:
                status: 400
                message: The value must be positive
    delete:
      summary: Delete an existing car
      tags:
        - Car controller
      parameters:
        - in: query
          name: carInDto
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            $ref: "#/components/schemas/CarInDto"
      responses:
        "200": # status code
          description: Successfully deleted an existing car
          content:
            application/json:
              schema:
                type: integer
              example:
                value: true
                responseTime: 10
        "400": # status code
          description: Car not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDTO" # Reference to an object
              example:
                status: 400
                message: The value must be positive
  /v1/car:
    post:
      summary: Add a new car
      tags:
        - Car controller
      parameters:
        - in: query
          name: carInDto
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            $ref: "#/components/schemas/CarInDto"
      responses:
        "200": # status code
          description: Successfully added a new car
          content:
            application/json:
              schema:
                type: integer
              example:
                value: true
                responseTime: 10
  /v1/motorcycles:
    get:
      summary: Get all the cars
      tags:
        - Motorcycle controller
      parameters:
        - in: query
          name: carInDto
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            $ref: "#/components/schemas/CarInDto"
      responses:
        "200": # status code
          description: Successfully retrieved some data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OkResponseDTO" # Reference to an object
              example:
                value: 2
                responseTime: 10
        "400": # status code
          description: Car not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDTO" # Reference to an object
              example:
                status: 400
                message: The value must be positive
  /v1/motorcycle/{motorcycleId}:
    get:
      summary: Find a car by id
      tags:
        - Motorcycle controller
      parameters:
        - in: path
          name: carId
          required: true
          schema:
            $ref: "#/components/schemas/PrimeInDTO" # Reference to an object
      responses:
        "200": # status code
          description: Successfully retrieved some data
          content:
            application/json:
              schema:
                type: integer
              example:
                value: true
                responseTime: 10
        "400": # status code
          description: Car not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDTO" # Reference to an object
              example:
                status: 400
                message: The value must be positive
    put:
      summary: Update an existing car
      tags:
        - Motorcycle controller
      parameters:
        - in: query
          name: carInDto
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            $ref: "#/components/schemas/CarInDto"
      responses:
        "200": # status code
          description: Successfully updated an existing car
          content:
            application/json:
              schema:
                type: integer
              example:
                value: true
                responseTime: 10
        "400": # status code
          description: Car not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDTO" # Reference to an object
              example:
                status: 400
                message: The value must be positive
    delete:
      summary: Delete an existing car
      tags:
        - Motorcycle controller
      parameters:
        - in: query
          name: carInDto
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            $ref: "#/components/schemas/CarInDto"
      responses:
        "200": # status code
          description: Successfully deleted an existing car
          content:
            application/json:
              schema:
                type: integer
              example:
                value: true
                responseTime: 10
        "400": # status code
          description: Car not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDTO" # Reference to an object
              example:
                status: 400
                message: The value must be positive
  /v1/motorcycle:
    post:
      summary: Add a new car
      tags:
        - Motorcycle controller
      parameters:
        - in: query
          name: carInDto
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            $ref: "#/components/schemas/CarInDto"
      responses:
        "200": # status code
          description: Successfully added a new car
          content:
            application/json:
              schema:
                type: integer
              example:
                value: true
                responseTime: 10
components:
  schemas:
    MotorcycleInDto:
      type: object
      properties:
        make:
          description: The calculated value
          type: string
          example: 4
        model:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        firstRegistrationFrom:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        price:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        mileage:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        fuelType:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        gearBox:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        power:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        bodyType:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
    ErrorResponse:
      type: object
      properties:
        status:
          description: The error status code
          type: integer
          example: 400
        message:
          description: The error message
          type: string
          example: "The value must be positive"
    MotorcycleOutDto:
      type: object
      properties:
        make:
          description: The calculated value
          type: string
          example: 4
        model:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        firstRegistrationFrom:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        price:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        mileage:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        fuelType:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        gearBox:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        power:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        bodyType:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        id:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
    CarInDto:
      type: object
      properties:
        make:
          description: The calculated value
          type: string
          example: 4
        model:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        firstRegistrationFrom:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        price:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        mileage:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        fuelType:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        gearBox:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        power:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        bodyType:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
    CarOutDto:
      type: object
      properties:
        make:
          description: The calculated value
          type: string
          example: 4
        model:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        firstRegistrationFrom:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        price:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        mileage:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        fuelType:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        gearBox:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        power:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        bodyType:
          description: The time in seconds to calculate the value
          type: integer
          example: 50
        id:
          description: The time in seconds to calculate the value
          type: integer
          example: 50